parameters:
  email_user: "%env(EMAIL_USERNAME)%"
  email_password: "%env(EMAIL_PASSWORD)%"
  email_smtp: "%env(EMAIL_SMTP)%"
  email_port: "%env(EMAIL_PORT)%"

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $em: "@doctrine.orm.entity_manager"

  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  App\Controller\:
    resource: "../src/Controller"
    tags: ["controller.service_arguments"]

  App\Service\EmailService:
    arguments:
      $emailUser: "%env(EMAIL_USERNAME)%"
      $emailPassword: "%env(EMAIL_PASSWORD)%"
      $emailSmtp: "%env(EMAIL_SMTP)%"
      $emailPort: "%env(EMAIL_PORT)%"
